databases:
  - name: ligdi-chat-db
    plan: free
    region: oregon

services:
  - type: web
    name: ligdi-chat-server
    env: docker
    dockerfilePath: server/Dockerfile
    dockerContext: server
    plan: free
    region: oregon
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ligdi-chat-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_ORIGIN
        value: "*"
